<div style="text-align:center; font-size:2rem">
КПІ ім. І. Сікорського<br>
Телпоенергетичний факультет<br>
Кафедра АПЕПС<br><br>
Лабораторна робота №30<br>
Варіант №4, 691, 700<br><br>
Виконав: <br>
студент гр. ТІ-81<br>
Галич Д.О.<br><br>
Перевірив:<br>
Сігайов А. О.<br><br>
Київ КПІ 2019<br>
</div>

## Варіант №4(691, 700)

### Завдання

691. Дано дійсні числа $a_1, ...,a_{64}$. Отримати дійсну квадратну
матрицю порядку 8, елементами якої є числа $a_1, ...,a_{64}$, розташовані в ній по схемі,
яка приведена на рис. 38, $а-г$.

![](C:\Users\Dima\Pictures\Безымянный.jpg)

In [1]:
a = [i for i in range(64)]
b = [[(a[8 * i + j] if i % 2 == 0 else a[8 * (i + 1) - j - 1]) for i in range(8)] for j in range(8)]
[print(b[i]) for i in range(8)]
b = [[(a[7 - i + j*8] if j % 2 == 0 else a[8 * j + i]) for i in range(8)] for j in range(8)]
[print(b[i]) for i in range(8)]

[0, 15, 16, 31, 32, 47, 48, 63]
[1, 14, 17, 30, 33, 46, 49, 62]
[2, 13, 18, 29, 34, 45, 50, 61]
[3, 12, 19, 28, 35, 44, 51, 60]
[4, 11, 20, 27, 36, 43, 52, 59]
[5, 10, 21, 26, 37, 42, 53, 58]
[6, 9, 22, 25, 38, 41, 54, 57]
[7, 8, 23, 24, 39, 40, 55, 56]
[7, 6, 5, 4, 3, 2, 1, 0]
[8, 9, 10, 11, 12, 13, 14, 15]
[23, 22, 21, 20, 19, 18, 17, 16]
[24, 25, 26, 27, 28, 29, 30, 31]
[39, 38, 37, 36, 35, 34, 33, 32]
[40, 41, 42, 43, 44, 45, 46, 47]
[55, 54, 53, 52, 51, 50, 49, 48]
[56, 57, 58, 59, 60, 61, 62, 63]


[None, None, None, None, None, None, None, None]

700. Дана квадратна матриця $A$ порядку $n$. Отримати матрицю $AB$; елементи матриці $B$ обчислюються
по формулі:

а) $b_{ij} = {1\over {i+j-1}}$;

б) \begin{equation*}
b_{ij} = 
 \begin{cases}
   {1\over {i+j-1}}, &\text{якщо $i \le j$},\\
   {1\over {i+j+1}} &\text{в іншому випадку;}
 \end{cases}
\end{equation*}

в) \begin{equation*}
b_{ij} = 
 \begin{cases}
   {1\over {i+j-1}}, &\text{якщо $i < j$},\\
   {0}, &\text{якщо $i=j$},\\
   -{1\over {i+j-1}} &\text{в інших випадках}
 \end{cases}
\end{equation*}

$(i, j = 1,...,n)$.

In [2]:
import numpy as np

n = int(input("Enter size: "))
a = np.array([[(i+1)*(j+1) for i in range(n)] for j in range(n)])
b = np.array([[1/(i+j-1) for i in range(1, n+1)] for j in range(1, n+1)])
print(a@b)
b = [[1/(i+j-1) if i <= j else 1/(i+j+1) for i in range(1, n+1)] for j in range(1, n+1)]
print(a@b)
b = [[1/(i+j-1) if i < j else (0 if i == j else -1/(i+j-1)) for i in range(1, n+1)] for j in range(1, n+1)]
print(a@b)

[[ 4.          2.71666667  2.1         1.72142857]
 [ 8.          5.43333333  4.2         3.44285714]
 [12.          8.15        6.3         5.16428571]
 [16.         10.86666667  8.4         6.88571429]]
[[ 4.          2.46666667  1.8         1.39880952]
 [ 8.          4.93333333  3.6         2.79761905]
 [12.          7.4         5.4         4.19642857]
 [16.          9.86666667  7.2         5.5952381 ]]
[[ 3.          1.05       -0.16666667 -1.15      ]
 [ 6.          2.1        -0.33333333 -2.3       ]
 [ 9.          3.15       -0.5        -3.45      ]
 [12.          4.2        -0.66666667 -4.6       ]]
